#!/bin/bash

echo "🔭 Telescope Weather App - Deployment Guide"
echo "=========================================="
echo ""
echo "Your app is ready for deployment! Choose one:"
echo ""
echo "1. VERCEL (Recommended - Free):"
echo "   - Install: npm i -g vercel"
echo "   - Run: vercel --prod"
echo "   - Your live URL will be provided"
echo ""
echo "2. RAILWAY (Alternative):"
echo "   - Visit: railway.app"
echo "   - Connect GitHub repo"
echo "   - Auto-deploy"
echo ""
echo "3. RENDER (Another option):"
echo "   - Visit: render.com"
echo "   - Connect GitHub repo"
echo "   - Choose Python web service"
echo ""
echo "Files ready for deployment:"
echo "✓ vercel.json (Vercel config)"
echo "✓ requirements.txt (Dependencies)"
echo "✓ app.py (Main application)"
echo "✓ templates/index.html (Frontend)"
echo "✓ CSV data file (Historical data)"
echo ""
echo "🌟 Your app will be live at: https://your-app-name.vercel.app"